name: Terraform Deploy RG + KeyVault

on:
  workflow_dispatch:
    inputs:
      rg_name:
        description: 'Resource Group Name'
        required: true
      kv_name:
        description: 'Key Vault Name'
        required: true
      location:
        description: 'Azure Location'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).appId }}
          ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).password }}
          ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenant }}
          ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).Subscriptionid }}
        run: terraform apply -auto-approve \
          -var="resource_group_name=${{ github.event.inputs.rg_name }}" \
          -var="key_vault_name=${{ github.event.inputs.kv_name }}" \
          -var="location=${{ github.event.inputs.location }}"


